### ISSUE TITLE
Invalid memory access

### ISSUE THREAD

**Issue by lyahim** [dren-dk/HunspellJNA#17]
Hello dren-dk!

Firstly thank you for your work and the nice tool!

I use the JNA library in tomcat container for process messages from social media. I have found a special case when the library kill the tomcat.

When I try to analize the smile 😂 I get Invalid memory access.

In windows environment:
Caused by: java.lang.Error: Invalid memory access
	at com.sun.jna.Native.invokeInt(Native Method) ~[jna-4.5.0.jar:4.5.0 (b0)]
	at com.sun.jna.Function.invoke(Function.java:419) ~[jna-4.5.0.jar:4.5.0 (b0)]
	at com.sun.jna.Function.invoke(Function.java:354) ~[jna-4.5.0.jar:4.5.0 (b0)]
	at com.sun.jna.Library$Handler.invoke(Library.java:244) ~[jna-4.5.0.jar:4.5.0 (b0)]
	at com.sun.proxy.$Proxy75.Hunspell_suggest(Unknown Source) ~[na:na]

I Linux:
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007f0030bb9fc8, pid=6855, tid=0x00007f000d4f9700
#
# JRE version: Java(TM) SE Runtime Environment (8.0_151-b12) (build 1.8.0_151-b12)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.151-b12 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libhunspell-linux-x86-64.so+0x27fc8]  SuggestMgr::leftcommonsubstring(char*, char const*)+0x108
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /opt/tomcat8/hs_err_pid6855.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```
Do you know about this behaviour? Do you know any workaround?

Best Regards,
Mihaly

**Comment by lyahim** [comment]
Thank you dren-dk,

 I selected the second case, but maybe Hunspell developsers known about the issue

https://github.com/hunspell/hunspell/issues/493

**Comment by alexisdoualle** [comment]
I had a similar error where a wrong dictionary format would cause my tomcat server to crash because of an invalid memory access, whenever I tried adding a new word to the dictionary instance.

```
# JRE version: Java(TM) SE Runtime Environment (8.0_101-b13) (build 1.8.0_101-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.101-b13 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libhunspell-linux-x86-64.so+0x1cd78]  HashMgr::hash(char const*) const+0x68
```

What I did was to add a test to check that the dictionary is the right format before instanciating it. The only thing that hunspell required is that the .dic file has only a number as the first line. The rest can be empty or gibberish, but if it doesn't start with a number, the Hash Manager would crash when adding a new word. This is more a problem with hunspell then with dren-dk's very useful API!

I know it's not exactly the problem you had, but it goes to show that input sanitization is the way to go here.
